### ISSUE TITLE
Issue with compiling T-Encoder Pro Example Sketches

### ISSUE THREAD

**Issue by arnie2321** [Xinyuan-LilyGO/T-Encoder-Pro#7]
I'm getting lots of errors when compiling the Lvgl_CIT sketch that I pulled from the GitHub examples folder for the T-Encoder Pro.  Mainly seems like issues with library dependencies.   A couple of the other example sketches, Rotary_Encoder and CHSC5816 do compile and run on the T-Encoder.  The GFX example won't compile either.   I'm working in Arduino IDE 2.3.1.  Help from the community or developer would be welcomed.

Lvgl_CIT Compile Errors: 

In file included from c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_GFX_Library.h:4,
                 from C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\custom.h:13,
                 from C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\Lvgl_CIT.ino:15:
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:13: error: 'i80_device_list' has not been declared
  167 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |             ^~~~~~~~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:3: error: ISO C++ forbids declaration of 'LIST_HEAD' with no type [-fpermissive]
  167 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |   ^~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:48: error: expected ';' at end of member declaration
  167 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |                                                ^
      |                                                 ;
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:168:3: error: 'device_list' does not name a type
  168 |   device_list; // Head of i80 device list
      |   ^~~~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:202:3: error: ISO C++ forbids declaration of 'LIST_ENTRY' with no type [-fpermissive]
  202 |   LIST_ENTRY(lcd_panel_io_i80_t)
      |   ^~~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:202:32: error: expected ';' at end of member declaration
  202 |   LIST_ENTRY(lcd_panel_io_i80_t)
      |                                ^
      |                                 ;
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:203:3: error: 'device_list_entry' does not name a type
  203 |   device_list_entry; // Entry of i80 device list
      |   ^~~~~~~~~~~~~~~~~
In file included from c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_GFX_Library.h:17:
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/databus/Arduino_ESP32RGBPanel.h:43:3: error: 'esp_lcd_rgb_panel_frame_trans_done_cb_t' does not name a type; did you mean 'esp_lcd_panel_io_color_trans_done_cb_t'?
   43 |   esp_lcd_rgb_panel_frame_trans_done_cb_t on_frame_trans_done; // Callback, invoked after frame trans done
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   esp_lcd_panel_io_color_trans_done_cb_t
C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\Lvgl_CIT.ino: In function 'void setup()':
C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\Lvgl_CIT.ino:142:5: error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?
  142 |     ledcAttachPin(BUZZER_DATA, 1);
      |     ^~~~~~~~~~~~~
      |     ledcAttach
C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\Lvgl_CIT.ino:143:5: error: 'ledcSetup' was not declared in this scope
  143 |     ledcSetup(1, 2000, 8);
      |     ^~~~~~~~~
In file included from c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_GFX_Library.h:4,
                 from C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\custom.h:13,
                 from C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\custom.cpp:14:
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:13: error: 'i80_device_list' has not been declared
  167 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |             ^~~~~~~~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:3: error: ISO C++ forbids declaration of 'LIST_HEAD' with no type [-fpermissive]
  167 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |   ^~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:167:48: error: expected ';' at end of member declaration
  167 |   LIST_HEAD(i80_device_list, lcd_panel_io_i80_t)
      |                                                ^
      |                                                 ;
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:168:3: error: 'device_list' does not name a type
  168 |   device_list; // Head of i80 device list
      |   ^~~~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:202:3: error: ISO C++ forbids declaration of 'LIST_ENTRY' with no type [-fpermissive]
  202 |   LIST_ENTRY(lcd_panel_io_i80_t)
      |   ^~~~~~~~~~
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:202:32: error: expected ';' at end of member declaration
  202 |   LIST_ENTRY(lcd_panel_io_i80_t)
      |                                ^
      |                                 ;
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_DataBus.h:203:3: error: 'device_list_entry' does not name a type
  203 |   device_list_entry; // Entry of i80 device list
      |   ^~~~~~~~~~~~~~~~~
In file included from c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/Arduino_GFX_Library.h:17:
c:\Users\MyPC\Documents\Arduino\libraries\Arduino_GFX-1.3.7\src/databus/Arduino_ESP32RGBPanel.h:43:3: error: 'esp_lcd_rgb_panel_frame_trans_done_cb_t' does not name a type; did you mean 'esp_lcd_panel_io_color_trans_done_cb_t'?
   43 |   esp_lcd_rgb_panel_frame_trans_done_cb_t on_frame_trans_done; // Callback, invoked after frame trans done
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   esp_lcd_panel_io_color_trans_done_cb_t
C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\custom.cpp: In function 'void Window_Rotary_Encoder_WS2812B_Test_Loop()':
C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\custom.cpp:316:17: error: 'ledcSetup' was not declared in this scope
  316 |                 ledcSetup(1, 1500, 8);
      |                 ^~~~~~~~~
C:\Users\MyPC\Documents\Arduino\T-Encoder-Pro-main\examples\Lvgl_CIT\custom.cpp:372:17: error: 'ledcSetup' was not declared in this scope
  372 |                 ledcSetup(1, 1500, 8);
      |                 ^~~~~~~~~

exit status 1

Compilation error: 'ledcAttachPin' was not declared in this scope; did you mean 'ledcAttach'?

**Comment by Llgok** [comment]
@arnie2321 
Currently, the T-Encoder-Pro example code only supports the arduino-esp32-libs_V2.0.14 version. Compiling with the arduino-esp32-libs_V2.0.14 version will not result in any errors.
